kind = "web"
previewPath = "/"
title = "Shopy"
version = "1.0.0"
id = "artifacts/shopy"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23234

[services.development]
run = "pnpm --filter @workspace/shopy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/shopy", "run", "build" ]
publicDir = "artifacts/shopy/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23234"
BASE_PATH = "/"
